CREATE DATABASE IF NOT EXISTS finder
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE finder;

CREATE TABLE IF NOT EXISTS url_analysis (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  url VARCHAR(2048) NOT NULL,
  risk_score INT,
  ml_result TEXT,
  multimodal_result TEXT,
  xai_result TEXT,
  screenshot_data LONGTEXT,
  final_result VARCHAR(32),
  processing_status VARCHAR(32) NOT NULL DEFAULT 'PROCESSING',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reports (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  url VARCHAR(2048) NOT NULL,
  reason TEXT,
  analysis_id BIGINT,
  domain VARCHAR(255),
  report_count INT NOT NULL DEFAULT 1,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
